# Inserts a blank line between shell prompts
add_newline = true

[character]                            
success_symbol = "[ »︁](bold fg:#d79921)"     
error_symbol = "[ »︁](bold red) "
vicmd_symbol = "[ ](fg:#d79921)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
style = "bold fg:#d79921"

[hostname]
ssh_only = false
format = "︁  [$hostname]($style)"
trim_at = "-"
style = "bold fg:#d79921"
disabled = true

[username]
style_user = "bold fg:#f2e5bc"
show_always = true

[python]
symbol = " "
pyenv_version_name = false
